version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    volumes:
      - ./honeypot/data:/app/data
      - ./honeypot/models:/app/models
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    command: uvicorn aetherion_app:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped

  honeypot:
    build: ./honeypot
    container_name: honeypot
    ports:
      - "2222:2222"
    volumes:
      - ./honeypot/data:/app/data
      - ./honeypot/models:/app/models
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    command: python server.py
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8001
      - VITE_HONEYPOT_URL=http://localhost:2222
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped